#!/usr/bin/env bash
# Compares example-owned Verilog goldens, verifies CIRCT IR, and simulates fixtures.
set -euo pipefail

mode="${1:-run}"
case "$mode" in
  run|--golden-only|--update-goldens) ;;
  *)
    echo "usage: $0 [--golden-only|--update-goldens]" >&2
    exit 2
    ;;
esac

repo_dir="$(cd "$(dirname "$0")/../.." && pwd)"
test_tmp_dir="$(mktemp -d /tmp/rhdl-circt.XXXXXX)"
trap 'rm -rf "$test_tmp_dir"' EXIT

circt_opt="${CIRCT_OPT:-$repo_dir/.tools/firtool-1.155.0/bin/circt-opt}"
if [[ ! -x "$circt_opt" ]]; then
  if command -v circt-opt >/dev/null 2>&1; then
    circt_opt="$(command -v circt-opt)"
  else
    echo "circt-opt not found; run 'make setup-circt' or set CIRCT_OPT" >&2
    exit 1
  fi
fi

cd "$repo_dir"

fixture_selected() {
  [[ -z "${FIXTURE:-}" || "$1" == "$FIXTURE" ]]
}

update_reference() {
  local source_file="$1"
  local reference_export="$2"
  local verilog="$3"
  local rewritten="$test_tmp_dir/updated-$(basename "$source_file")"
  local marker="def $reference_export = @str|<<{"
  local marker_count

  marker_count="$(grep -Fxc "$marker" "$source_file" || true)"
  if [[ "$marker_count" != 1 ]]; then
    echo "$source_file must contain exactly one '$marker' line" >&2
    exit 1
  fi

  awk -v marker="$marker" -v replacement="$verilog" '
    $0 == marker {
      print
      while ((getline line < replacement) > 0) print line
      replacing = 1
      next
    }
    replacing && $0 == "}>>|" {
      print
      replacing = 0
      next
    }
    !replacing { print }
    END { if (replacing) exit 2 }
  ' "$source_file" > "$rewritten"
  mv "$rewritten" "$source_file"
}

prepare_example() {
  local fixture="$1"
  local example="$2"
  local reference_export="$3"
  local mlir="$test_tmp_dir/$fixture.mlir"
  local verilog="$test_tmp_dir/$fixture.sv"
  local expected="$test_tmp_dir/$fixture.expected.sv"
  local memory_lowering_pass=""

  "$circt_opt" "$mlir" -o /dev/null
  if grep -q 'seq.hlmem' "$mlir"; then
    memory_lowering_pass=--lower-seq-hlmem
  fi
  "$circt_opt" --strip-debuginfo-with-pred='drop-suffix=.mlir' \
    --prettify-verilog \
    $memory_lowering_pass \
    --lower-seq-to-sv='disable-reg-randomization=true' \
    --export-verilog "$mlir" -o /dev/null \
    | sed '1{/^\/\/ Generated by CIRCT /d;}' \
    | perl -0pe 's/\n+\z//' > "$verilog"

  if [[ "$mode" == --update-goldens ]]; then
    update_reference "$example" "$reference_export" "$verilog"
    return 0
  fi

  if ! diff -u --label "$example:$reference_export" \
      --label "generated $fixture Verilog" "$expected" "$verilog"; then
    echo "$fixture Verilog differs from its example-owned reference" >&2
    exit 1
  fi
}

golden_fixture() {
  local fixture="$1"
  local example="$2"
  local design_export="${3:-design}"
  local reference_export="${4:-verilog_reference}"

  fixture_selected "$fixture" || return 0
  prepare_example "$fixture" "$example" "$reference_export"
}

run_fixture() {
  local fixture="$1"
  local top="$2"
  local example="$3"
  local design_export="${4:-design}"
  local reference_export="${5:-verilog_reference}"
  local verilog="$test_tmp_dir/$fixture.sv"
  local object_dir="$test_tmp_dir/${fixture}_obj"
  local build_log="$test_tmp_dir/$fixture.verilator.log"

  fixture_selected "$fixture" || return 0
  prepare_example "$fixture" "$example" "$reference_export"
  [[ "$mode" == run ]] || return 0

  if ! verilator --binary --timing --build-jobs 0 --top-module "$top" \
      --Mdir "$object_dir" \
      "$verilog" "tests/backend/verilog/${fixture}_tb.sv" \
      > "$build_log" 2>&1; then
    cat "$build_log" >&2
    return 1
  fi
  "$object_dir/V$top"
}

verify_fixture() {
  local fixture="$1"
  local top="${2:-}"
  local mlir="$test_tmp_dir/$fixture.mlir"
  local verilog="$test_tmp_dir/$fixture.sv"
  local memory_lowering_pass=""
  local object_dir="$test_tmp_dir/${fixture}_obj"
  local build_log="$test_tmp_dir/$fixture.verilator.log"

  fixture_selected "$fixture" || return 0
  [[ "$mode" == run ]] || return 0

  racket -S "$repo_dir" "tests/backend/emit-$fixture.rhm" > "$mlir"
  "$circt_opt" "$mlir" -o /dev/null
  if grep -q 'seq.hlmem' "$mlir"; then
    memory_lowering_pass=--lower-seq-hlmem
  fi
  "$circt_opt" --prettify-verilog \
    $memory_lowering_pass \
    --lower-seq-to-sv='disable-reg-randomization=true' \
    --export-verilog "$mlir" -o /dev/null > "$verilog"

  if [[ -n "$top" ]]; then
    if ! verilator --binary --timing --build-jobs 0 --top-module "$top" \
        --Mdir "$object_dir" \
        "$verilog" "tests/backend/verilog/${fixture}_tb.sv" \
        > "$build_log" 2>&1; then
      cat "$build_log" >&2
      return 1
    fi
    "$object_dir/V$top"
  fi
}

fixture_specs=(
  'adder|adder_tb|examples/lop/adder-standard.rhdl|design|verilog_reference'
  'adder4|adder4_tb|examples/adder4.rhdl|design|verilog_reference'
  'generated-adder|generated_adder_tb|examples/generated-adder.rhdl|design|verilog_reference'
  'alu|alu_tb|examples/alu.rhdl|design|verilog_reference'
  'enum-state||examples/enum-state.rhdl|design|verilog_reference'
  'shifts|shifts_tb|examples/shifts.rhdl|design|verilog_reference'
  'width-ops|width_ops_tb|examples/width-ops.rhdl|design|verilog_reference'
  'vector|vector_tb|examples/vector.rhdl|design|verilog_reference'
  'vec-shift-register|vec_shift_register_tb|examples/vec-shift-register.rhdl|design|verilog_reference'
  'wire|wire_tb|examples/wire.rhdl|design|verilog_reference'
  'async-read-memory|async_read_memory_tb|examples/async-read-memory.rhdl|design|verilog_reference'
  'tiny-simd|tiny_simd_tb|examples/tiny-simd.rhdl|design|verilog_reference'
  'stack|stack_tb|examples/stack.rhdl|design|verilog_reference'
  'counter|counter_tb|examples/counter.rhdl|design|verilog_reference'
  'multiply|multiply_tb|examples/multiply.rhdl|design|verilog_reference'
  'expanding-arithmetic|expanding_arithmetic_tb|examples/expanding-arithmetic.rhdl|design|verilog_reference'
  'unsigned-comparisons|unsigned_comparisons_tb|examples/unsigned-comparisons.rhdl|design|verilog_reference'
  'sync-counter||examples/sync-counter.rhdl|design|verilog_reference'
  'enable-shift-register|enable_shift_register_tb|examples/enable-shift-register.rhdl|design|verilog_reference'
  'reset-shift-register|reset_shift_register_tb|examples/reset-shift-register.rhdl|design|verilog_reference'
  'hierarchy|hierarchy_tb|examples/hierarchy.rhdl|design|verilog_reference'
  'bundle|bundle_tb|examples/bundle.rhdl|design|verilog_reference'
  'record-cast|record_cast_tb|examples/bundle.rhdl|cast_design|cast_verilog_reference'
  'interface|interface_tb|examples/interface.rhdl|design|verilog_reference'
  'nested-interface|nested_interface_tb|examples/nested-interface.rhdl|design|verilog_reference'
  'full-adder||examples/full-adder.rhdl|design|verilog_reference'
  'layered-adder||examples/layered-adder.rhdl|design|verilog_reference'
  'host-parameters||examples/host-parameters.rhdl|design|verilog_reference'
  'fresh-generators||examples/fresh-generators.rhdl|design|verilog_reference'
)

materialize_args=()
for spec in "${fixture_specs[@]}"; do
  IFS='|' read -r fixture top example design_export reference_export <<< "$spec"
  if fixture_selected "$fixture"; then
    materialize_args+=("$fixture" "$example" "$design_export" "$reference_export")
  fi
done

if (( ${#materialize_args[@]} > 0 )); then
  racket -S "$repo_dir" tests/backend/load-example.rkt \
    materialize "$test_tmp_dir" "${materialize_args[@]}"
fi

for spec in "${fixture_specs[@]}"; do
  IFS='|' read -r fixture top example design_export reference_export <<< "$spec"
  if [[ -n "$top" ]]; then
    run_fixture "$fixture" "$top" "$example" "$design_export" "$reference_export"
  else
    golden_fixture "$fixture" "$example" "$design_export" "$reference_export"
  fi
done

verify_fixture nested-bundle
verify_fixture bundle-hierarchy
verify_fixture interface-hierarchy
verify_fixture aggregate-memory
verify_fixture table table_tb
verify_fixture vec-search vec_search_tb
