#!/usr/bin/env bash
# Compares example-owned Verilog goldens, verifies CIRCT IR, and simulates fixtures.
set -euo pipefail

mode="${1:-run}"
case "$mode" in
  run|--golden-only|--update-goldens) ;;
  *)
    echo "usage: $0 [--golden-only|--update-goldens]" >&2
    exit 2
    ;;
esac

repo_dir="$(cd "$(dirname "$0")/../.." && pwd)"
test_tmp_dir="$(mktemp -d /tmp/rhdl-circt.XXXXXX)"
trap 'rm -rf "$test_tmp_dir"' EXIT

circt_opt="${CIRCT_OPT:-$repo_dir/.tools/firtool-1.155.0/bin/circt-opt}"
if [[ ! -x "$circt_opt" ]]; then
  if command -v circt-opt >/dev/null 2>&1; then
    circt_opt="$(command -v circt-opt)"
  else
    echo "circt-opt not found; run 'make setup-circt' or set CIRCT_OPT" >&2
    exit 1
  fi
fi

golden_circt_version="firtool-1.155.0"
circt_version="$("$circt_opt" --version | sed -n 's/^CIRCT //p')"
compare_goldens=true
if [[ "$circt_version" != "$golden_circt_version" ]]; then
  if [[ "$mode" == --golden-only ]]; then
    echo "Verilog goldens require CIRCT $golden_circt_version; found ${circt_version:-an unknown version}" >&2
    exit 1
  fi
  compare_goldens=false
  echo "CIRCT ${circt_version:-version unknown}: skipping version-specific Verilog golden comparisons"
fi

cd "$repo_dir"

fixture_selected() {
  [[ -z "${FIXTURE:-}" || "$1" == "$FIXTURE" ]]
}

update_reference() {
  local source_file="$1"
  local reference_export="$2"
  local verilog="$3"
  local rewritten="$test_tmp_dir/updated-$(basename "$source_file")"
  local marker="def $reference_export = @str|<<{"
  local marker_count

  marker_count="$(grep -Fxc "$marker" "$source_file" || true)"
  if [[ "$marker_count" != 1 ]]; then
    echo "$source_file must contain exactly one '$marker' line" >&2
    exit 1
  fi

  awk -v marker="$marker" -v replacement="$verilog" '
    $0 == marker {
      print
      while ((getline line < replacement) > 0) print line
      replacing = 1
      next
    }
    replacing && $0 == "}>>|" {
      print
      replacing = 0
      next
    }
    !replacing { print }
    END { if (replacing) exit 2 }
  ' "$source_file" > "$rewritten"
  mv "$rewritten" "$source_file"
}

prepare_example() {
  local fixture="$1"
  local example="$2"
  local reference_export="$3"
  local mlir="$test_tmp_dir/$fixture.mlir"
  local verilog="$test_tmp_dir/$fixture.sv"
  local expected="$test_tmp_dir/$fixture.expected.sv"
  local has_firmem=false
  local -a circt_args=(
    --strip-debuginfo-with-pred='drop-suffix=.mlir'
    --canonicalize
    --cse
    --prettify-verilog
  )

  "$circt_opt" "$mlir" -o /dev/null
  if grep -q 'seq.hlmem' "$mlir"; then
    circt_args+=(--lower-seq-hlmem)
  fi
  if grep -q 'seq.firmem' "$mlir"; then
    circt_args+=(--lower-seq-firmem)
    has_firmem=true
  fi
  circt_args+=(
    --lower-sim-to-sv
    --lower-verif-to-sv
    --lower-seq-to-sv='disable-mem-randomization=true disable-reg-randomization=true'
  )
  if [[ "$has_firmem" == true ]]; then
    circt_args+=(--hw-memory-sim='disable-mem-randomization=true disable-reg-randomization=true read-enable-mode=undefined')
  fi
  circt_args+=(--sv-mask-non-synthesizable='mode=ifdef macro=SYNTHESIS')
  circt_args+=(--export-verilog)
  "$circt_opt" "${circt_args[@]}" "$mlir" -o /dev/null \
    | sed -e '1{/^\/\/ Generated by CIRCT /d;}' \
          -e '/^\/\/ VCS coverage exclude_file$/d' \
    | perl -0pe 's/\n+\z//' > "$verilog"

  if [[ "$mode" == --update-goldens ]]; then
    update_reference "$example" "$reference_export" "$verilog"
    return 0
  fi

  if [[ "$compare_goldens" != true ]]; then
    return 0
  fi

  if ! diff -u --label "$example:$reference_export" \
      --label "generated $fixture Verilog" "$expected" "$verilog"; then
    echo "$fixture Verilog differs from its example-owned reference" >&2
    exit 1
  fi
}

golden_fixture() {
  local fixture="$1"
  local example="$2"
  local design_export="${3:-design}"
  local reference_export="${4:-verilog_reference}"

  fixture_selected "$fixture" || return 0
  prepare_example "$fixture" "$example" "$reference_export"
}

run_fixture() {
  local fixture="$1"
  local top="$2"
  local example="$3"
  local design_export="${4:-design}"
  local reference_export="${5:-verilog_reference}"
  local verilog="$test_tmp_dir/$fixture.sv"
  local object_dir="$test_tmp_dir/${fixture}_obj"
  local build_log="$test_tmp_dir/$fixture.verilator.log"
  local dpi_source="$repo_dir/tests/backend/verilog/${fixture}_dpi.cpp"

  fixture_selected "$fixture" || return 0
  prepare_example "$fixture" "$example" "$reference_export"
  [[ "$mode" == run ]] || return 0

  local verilator_args=(
    --binary --timing --assert --build-jobs 0 --top-module "$top"
    --Mdir "$object_dir"
    "$verilog" "tests/backend/verilog/${fixture}_tb.sv"
  )
  if [[ -f "$dpi_source" ]]; then
    verilator_args+=("$dpi_source")
  fi

  if ! verilator "${verilator_args[@]}" > "$build_log" 2>&1; then
    cat "$build_log" >&2
    return 1
  fi
  "$object_dir/V$top"
}

run_expected_assertion_failure() {
  local fixture="$1"
  local top="$2"
  local testbench="$3"
  local expected_label="$4"
  local verilog="$test_tmp_dir/$fixture.sv"
  local object_dir="$test_tmp_dir/${fixture}_failure_obj"
  local build_log="$test_tmp_dir/$fixture.failure.verilator.log"
  local run_log="$test_tmp_dir/$fixture.failure.run.log"

  fixture_selected "$fixture" || return 0
  [[ "$mode" == run ]] || return 0

  if ! verilator --binary --timing --assert --build-jobs 0 --top-module "$top" \
      --Mdir "$object_dir" \
      "$verilog" "$testbench" \
      > "$build_log" 2>&1; then
    cat "$build_log" >&2
    return 1
  fi
  if bash -c '"$1"; status=$?; :; exit "$status"' _ "$object_dir/V$top" \
      > "$run_log" 2>&1; then
    echo "$fixture assertion failure simulation unexpectedly succeeded" >&2
    return 1
  fi
  if ! grep -q "$expected_label" "$run_log"; then
    echo "$fixture assertion failure did not report $expected_label" >&2
    cat "$run_log" >&2
    return 1
  fi
}

verify_fixture() {
  local fixture="$1"
  local top="${2:-}"
  local mlir="$test_tmp_dir/$fixture.mlir"
  local verilog="$test_tmp_dir/$fixture.sv"
  local has_firmem=false
  local -a circt_args=(
    --canonicalize
    --cse
    --prettify-verilog
  )
  local object_dir="$test_tmp_dir/${fixture}_obj"
  local build_log="$test_tmp_dir/$fixture.verilator.log"

  fixture_selected "$fixture" || return 0
  [[ "$mode" == run ]] || return 0

  racket -S "$repo_dir" "tests/backend/emit-$fixture.rhm" > "$mlir"
  "$circt_opt" "$mlir" -o /dev/null
  if grep -q 'seq.hlmem' "$mlir"; then
    circt_args+=(--lower-seq-hlmem)
  fi
  if grep -q 'seq.firmem' "$mlir"; then
    circt_args+=(--lower-seq-firmem)
    has_firmem=true
  fi
  circt_args+=(
    --lower-sim-to-sv
    --lower-verif-to-sv
    --lower-seq-to-sv='disable-mem-randomization=true disable-reg-randomization=true'
  )
  if [[ "$has_firmem" == true ]]; then
    circt_args+=(--hw-memory-sim='disable-mem-randomization=true disable-reg-randomization=true read-enable-mode=undefined')
  fi
  circt_args+=(--sv-mask-non-synthesizable='mode=ifdef macro=SYNTHESIS')
  circt_args+=(--export-verilog)
  "$circt_opt" "${circt_args[@]}" "$mlir" -o /dev/null > "$verilog"

  if [[ -n "$top" ]]; then
    if ! verilator --binary --timing --assert --build-jobs 0 --top-module "$top" \
        --Mdir "$object_dir" \
        "$verilog" "tests/backend/verilog/${fixture}_tb.sv" \
        > "$build_log" 2>&1; then
      cat "$build_log" >&2
      return 1
    fi
    "$object_dir/V$top"
  fi
}

fixture_specs=(
  'adder|adder_tb|examples/lop/adder-standard.rhdl|design|verilog_reference'
  'adder4|adder4_tb|examples/adder4.rhdl|design|verilog_reference'
  'generated-adder|generated_adder_tb|examples/generated-adder.rhdl|design|verilog_reference'
  'alu|alu_tb|examples/alu.rhdl|design|verilog_reference'
  'enum-state|enum_state_tb|examples/enum-state.rhdl|design|verilog_reference'
  'enum-state-lookup||examples/enum-state.rhdl|lookup_design|lookup_verilog_reference'
  'enum-opcode||examples/enum-state.rhdl|opcode_design|opcode_verilog_reference'
  'one-hot|one_hot_tb|examples/one-hot.rhdl|design|verilog_reference'
  'one-hot-enum||examples/one-hot-enum.rhdl|design|verilog_reference'
  'shifts|shifts_tb|examples/shifts.rhdl|design|verilog_reference'
  'width-ops|width_ops_tb|examples/width-ops.rhdl|design|verilog_reference'
  'vector|vector_tb|examples/vector.rhdl|design|verilog_reference'
  'vector-carry||examples/vector.rhdl|carry_design|carry_verilog_reference'
  'vector-update|vector_update_tb|examples/vector-update.rhdl|design|verilog_reference'
  'vector-register-update||examples/vector-update.rhdl|register_design|register_verilog_reference'
  'vec-shift-register|vec_shift_register_tb|examples/vec-shift-register.rhdl|design|verilog_reference'
  'vec-shift-register-param|vec_shift_register_param_tb|examples/vec-shift-register-param.rhdl|design|verilog_reference'
  'predicate-filter|predicate_filter_tb|examples/predicate-filter.rhdl|design|verilog_reference'
  'wire|wire_tb|examples/wire.rhdl|design|verilog_reference'
  'async-read-memory|async_read_memory_tb|examples/async-read-memory.rhdl|design|verilog_reference'
  'sync-memory|sync_memory_tb|examples/sync-memory.rhdl|design|verilog_reference'
  'sync-memory-1rw|sync_memory_1rw_tb|examples/sync-memory-1rw.rhdl|design|verilog_reference'
  'sync-memory-masked|sync_memory_masked_tb|examples/sync-memory-masked.rhdl|design|verilog_reference'
  'simple-memory||examples/simple-memory.rhdl|design|verilog_reference'
  'simple-memory-alignment||examples/simple-memory.rhdl|alignment_design|alignment_verilog_reference'
  'simple-memory-activity||examples/simple-memory.rhdl|activity_design|activity_verilog_reference'
  'simple-memory-flow||examples/simple-memory-flow.rhdl|design|verilog_reference'
  'simple-memory-ram|simple_memory_ram_tb|examples/simple-memory-ram.rhdl|design|verilog_reference'
  'multi-write-memory|multi_write_memory_tb|examples/multi-write-memory.rhdl|design|verilog_reference'
  'clocked-dpi|clocked_dpi_tb|examples/clocked-dpi.rhdl|design|verilog_reference'
  'clocked-dpi-always||examples/clocked-dpi.rhdl|always_design|always_verilog_reference'
  'clocked-dpi-explicit||examples/clocked-dpi.rhdl|explicit_design|explicit_verilog_reference'
  'assertions|assertions_tb|examples/assertions.rhdl|design|verilog_reference'
  'tiny-simd|tiny_simd_tb|examples/tiny-simd.rhdl|design|verilog_reference'
  'tiny-simd-no-multiply||examples/tiny-simd.rhdl|no_multiply_design|no_multiply_verilog_reference'
  'stack|stack_tb|examples/stack.rhdl|design|verilog_reference'
  'counter|counter_tb|examples/counter.rhdl|design|verilog_reference'
  'standard-counter|standard_counter_tb|examples/standard-counter.rhdl|design|verilog_reference'
  'multiply|multiply_tb|examples/multiply.rhdl|design|verilog_reference'
  'expanding-arithmetic|expanding_arithmetic_tb|examples/expanding-arithmetic.rhdl|design|verilog_reference'
  'unsigned-comparisons|unsigned_comparisons_tb|examples/unsigned-comparisons.rhdl|design|verilog_reference'
  'signed-integers|signed_integers_tb|examples/signed-integers.rhdl|design|verilog_reference'
  'sync-counter||examples/sync-counter.rhdl|design|verilog_reference'
  'sync-counter-resetless||examples/sync-counter.rhdl|resetless_design|resetless_verilog_reference'
  'sync-counter-explicit-clock||examples/sync-counter.rhdl|explicit_clock_design|explicit_clock_verilog_reference'
  'enable-shift-register|enable_shift_register_tb|examples/enable-shift-register.rhdl|design|verilog_reference'
  'reset-shift-register|reset_shift_register_tb|examples/reset-shift-register.rhdl|design|verilog_reference'
  'hierarchy|hierarchy_tb|examples/hierarchy.rhdl|design|verilog_reference'
  'rfpl-circuit-pair||examples/rfpl/circuit-pair.rhdl|design|verilog_reference'
  'nested-circuit|nested_circuit_tb|examples/nested-circuit.rhdl|design|verilog_reference'
  'bundle|bundle_tb|examples/bundle.rhdl|design|verilog_reference'
  'record-cast|record_cast_tb|examples/bundle.rhdl|cast_design|cast_verilog_reference'
  'bundle-specialization-types||examples/bundle.rhdl|specialization_design|specialization_verilog_reference'
  'bundle-nested-swap||examples/bundle.rhdl|nested_swap_design|nested_swap_verilog_reference'
  'bundle-hierarchy||examples/bundle.rhdl|hierarchy_design|hierarchy_verilog_reference'
  'interface|interface_tb|examples/interface.rhdl|design|verilog_reference'
  'interface-hierarchy||examples/interface.rhdl|hierarchy_design|hierarchy_verilog_reference'
  'interface-specialization||examples/interface-specialization.rhdl|design|verilog_reference'
  'interface-specialization-reversed||examples/interface-specialization.rhdl|reversed_design|reversed_verilog_reference'
  'interface-specialization-nested||examples/interface-specialization.rhdl|nested_design|nested_verilog_reference'
  'interface-specialization-width-adapter||examples/interface-specialization.rhdl|width_adapter_design|width_adapter_verilog_reference'
  'ready-valid-compatibility||examples/ready-valid-compatibility.rhdl|design|verilog_reference'
  'interface-array|interface_array_tb|examples/interface-array.rhdl|design|verilog_reference'
  'interface-generic-handle||examples/interface-array.rhdl|generic_handle_design|generic_handle_verilog_reference'
  'interface-parallel-handle||examples/interface-array.rhdl|parallel_handle_design|parallel_handle_verilog_reference'
  'interface-parallel-sink||examples/interface-array.rhdl|parallel_sink_design|parallel_sink_verilog_reference'
  'interface-array-hierarchy||examples/interface-array.rhdl|hierarchy_design|hierarchy_verilog_reference'
  'interface-array-sequence||examples/interface-array.rhdl|sequence_design|sequence_verilog_reference'
  'nested-interface|nested_interface_tb|examples/nested-interface.rhdl|design|verilog_reference'
  'nested-interface-member||examples/nested-interface.rhdl|member_design|member_verilog_reference'
  'nested-interface-deep||examples/nested-interface.rhdl|deep_design|deep_verilog_reference'
  'nested-interface-hierarchy||examples/nested-interface.rhdl|hierarchy_design|hierarchy_verilog_reference'
  'pipe|pipe_tb|examples/flow-control.rhdl|pipe_design|pipe_verilog_reference'
  'queue|queue_tb|examples/flow-control.rhdl|queue_design|queue_verilog_reference'
  'queue-one|queue_one_tb|examples/flow-control.rhdl|queue_one_design|queue_one_verilog_reference'
  'queue-options|queue_options_tb|examples/flow-control.rhdl|queue_options_design|queue_options_verilog_reference'
  'arbiter|arbiter_tb|examples/flow-control.rhdl|arbiter_design|arbiter_verilog_reference'
  'flow-chain|flow_chain_tb|examples/flow-control.rhdl|chain_design|chain_verilog_reference'
  'rr-arbiter|rr_arbiter_tb|examples/flow-topology.rhdl|rr_arbiter_design|rr_arbiter_verilog_reference'
  'demux|demux_tb|examples/flow-topology.rhdl|demux_design|demux_verilog_reference'
  'join|join_tb|examples/flow-topology.rhdl|join_design|join_verilog_reference'
  'broadcast|broadcast_tb|examples/flow-topology.rhdl|broadcast_design|broadcast_verilog_reference'
  'atomic-fork|atomic_fork_tb|examples/flow-topology.rhdl|atomic_fork_design|atomic_fork_verilog_reference'
  'flow-map|flow_map_tb|examples/flow-topology.rhdl|flow_map_design|flow_map_verilog_reference'
  'flow-filter||examples/flow-topology.rhdl|filter_flow_design|filter_flow_verilog_reference'
  'flow-gate||examples/flow-topology.rhdl|gate_flow_design|gate_flow_verilog_reference'
  'flow-endpoint-first||examples/flow-topology.rhdl|endpoint_first_design|endpoint_first_verilog_reference'
  'flow-fan-in-project||examples/flow-topology.rhdl|fan_in_project_design|fan_in_project_verilog_reference'
  'flow-zip-route||examples/flow-topology.rhdl|zip_route_design|zip_route_verilog_reference'
  'ctrl-pipe|ctrl_pipe_tb|examples/ctrl-flow.rhdl|ctrl_pipe_design|ctrl_pipe_verilog_reference'
  'ctrl-queue|ctrl_queue_tb|examples/ctrl-flow.rhdl|ctrl_queue_design|ctrl_queue_verilog_reference'
  'ctrl-queue-options|ctrl_queue_options_tb|examples/ctrl-flow.rhdl|ctrl_queue_options_design|ctrl_queue_options_verilog_reference'
  'ctrl-arbiter|ctrl_arbiter_tb|examples/ctrl-flow.rhdl|ctrl_arbiter_design|ctrl_arbiter_verilog_reference'
  'ctrl-rr-arbiter|ctrl_rr_arbiter_tb|examples/ctrl-flow.rhdl|ctrl_rr_arbiter_design|ctrl_rr_arbiter_verilog_reference'
  'ctrl-demux|ctrl_demux_tb|examples/ctrl-flow.rhdl|ctrl_demux_design|ctrl_demux_verilog_reference'
  'ctrl-join|ctrl_join_tb|examples/ctrl-flow.rhdl|ctrl_join_design|ctrl_join_verilog_reference'
  'ctrl-broadcast|ctrl_broadcast_tb|examples/ctrl-flow.rhdl|ctrl_broadcast_design|ctrl_broadcast_verilog_reference'
  'ctrl-chain||examples/ctrl-flow.rhdl|ctrl_chain_design|ctrl_chain_verilog_reference'
  'full-adder||examples/full-adder.rhdl|design|verilog_reference'
  'adder-core||examples/lop/adder-core.rhm|design|verilog_reference'
  'adder-kernel||examples/lop/adder-kernel.rhm|design|verilog_reference'
  'adder-composed||examples/lop/adder-composed.rhdl|design|verilog_reference'
  'bundle-kernel||examples/lop/bundle-kernel.rhdl|design|verilog_reference'
  'bundle-standard||examples/lop/bundle-standard.rhdl|design|verilog_reference'
  'interface-records||examples/lop/interface-records.rhdl|design|verilog_reference'
  'width-ops-kernel||examples/lop/width-ops-kernel.rhm|design|verilog_reference'
  'layered-adder||examples/layered-adder.rhdl|design|verilog_reference'
  'host-parameters||examples/host-parameters.rhdl|design|verilog_reference'
  'fresh-generators||examples/fresh-generators.rhdl|design|verilog_reference'
  'dont-care||examples/dont-care.rhdl|design|verilog_reference'
  'decode|decode_tb|examples/decode.rhdl|design|verilog_reference'
  'decode-composition||examples/decode-composition.rhdl|design|verilog_reference'
  'generator-ordinary-defaults||examples/generator-parameters.rhdl|ordinary_defaults_design|ordinary_defaults_verilog_reference'
  'generator-ordinary-overrides||examples/generator-parameters.rhdl|ordinary_overrides_design|ordinary_overrides_verilog_reference'
  'generator-ordinary-typed-defaults||examples/generator-parameters.rhdl|ordinary_typed_defaults_design|ordinary_typed_defaults_verilog_reference'
  'generator-ordinary-required-keyword||examples/generator-parameters.rhdl|ordinary_required_keyword_design|ordinary_required_keyword_verilog_reference'
  'generator-sync-defaults||examples/generator-parameters.rhdl|sync_defaults_design|sync_defaults_verilog_reference'
  'generator-sync-overrides||examples/generator-parameters.rhdl|sync_overrides_design|sync_overrides_verilog_reference'
  'generator-sync-typed-defaults||examples/generator-parameters.rhdl|sync_typed_defaults_design|sync_typed_defaults_verilog_reference'
  'register-forms||examples/register-forms.rhdl|design|verilog_reference'
  'sync-ram|sync_ram_tb|examples/sync-ram.rhdl|design|verilog_reference'
  'table||examples/table.rhdl|design|verilog_reference'
  'tilelink-uncached||examples/tilelink.rhdl|uncached_design|uncached_verilog_reference'
  'tilelink-cached||examples/tilelink.rhdl|cached_design|cached_verilog_reference'
  'valid-pipe||examples/valid-pipe.rhdl|design|verilog_reference'
  'vec-search||examples/vec-search.rhdl|design|verilog_reference'
)

materialize_args=()
for spec in "${fixture_specs[@]}"; do
  IFS='|' read -r fixture top example design_export reference_export <<< "$spec"
  if fixture_selected "$fixture"; then
    materialize_args+=("$fixture" "$example" "$design_export" "$reference_export")
  fi
done

if (( ${#materialize_args[@]} > 0 )); then
  RHDL_ESPRESSO=off racket -S "$repo_dir" tests/backend/load-example.rkt \
    materialize "$test_tmp_dir" "${materialize_args[@]}"
fi

for spec in "${fixture_specs[@]}"; do
  IFS='|' read -r fixture top example design_export reference_export <<< "$spec"
  if [[ -n "$top" ]]; then
    run_fixture "$fixture" "$top" "$example" "$design_export" "$reference_export"
  else
    golden_fixture "$fixture" "$example" "$design_export" "$reference_export"
  fi
done

run_expected_assertion_failure assertions assertions_fail_tb \
  tests/backend/verilog/assertions_fail_tb.sv request_holds

verify_fixture nested-bundle
verify_fixture bundle-hierarchy
verify_fixture interface-hierarchy
verify_fixture aggregate-memory
verify_fixture one-hot-aggregate
if espresso_path="$(command -v espresso 2>/dev/null)"; then
  RHDL_ESPRESSO="$espresso_path" verify_fixture decode-espresso decode_espresso_tb
fi
verify_fixture table table_tb
verify_fixture vec-search vec_search_tb
verify_fixture rv64i-alu rv64i_alu_tb
verify_fixture rv64i-alu-decode
verify_fixture rv64i-alu-integrated rv64i_alu_integrated_tb
verify_fixture valid-pipe valid_pipe_tb
verify_fixture tilelink-ram tilelink_ram_tb
run_expected_assertion_failure tilelink-ram tilelink_ram_invalid_tb \
  tests/backend/verilog/tilelink-ram-invalid_tb.sv tilelink_a_mask_supported
verify_fixture load-store load_store_tb
verify_fixture ricket-register-file ricket_register_file_tb
verify_fixture ricket-scoreboard ricket_scoreboard_tb
verify_fixture ricket-pipeline ricket_pipeline_tb
verify_fixture ricket-icache ricket_icache_tb
verify_fixture ricket-dcache ricket_dcache_tb
